### ISSUE TITLE
Nativescripts project: ios-device-lib has conflicting provisioning settings

### ISSUE THREAD

**Issue by TimHawkHodg** [telerik/ios-device-lib#36] opened 2018-01-16 01:21 UTC
Hello whenever I run my native scripts project I get the error

`"error: exportArchive: adb has conflicting provisioning settings.
Error Domain=IDEProvisioningErrorDomain Code=8 "adb has conflicting provisioning settings.
ios-device-lib has conflicting provisioning settings.\" UserInfo={NSLocalizedDescription=ios-device-lib has conflicting provisioning settings., NSLocalizedRecoverySuggestion=ios-device-lib is automatically signed for distribution, but a conflicting code signing identity iPhone Developer has been manually specified. Remove the \"signingCertificate\" entry from your Export Options property list, or switch to manual signing by setting \"signingStyle\" to \"Manual.}"`

Is there a way to explicitly set the provisioning profile for ios-device-lib to avoid this error?

**Comment by rosen-vladimirov** [comment] 2018-01-16 09:26
Hey @TimHawkHodg ,
The message you've faced is a standard from Xcode when Automatic codesign is used and there's executable in you project that should be included in the built `.ipa` file. In order to resolve it, you have to use Manual signing. You can do this by using `--provision` flag of `tns build ios` (available in `tns run ios` as well) command.
By the way, the error message indicates you've included the `ios-device-lib` in your NativeScript project. The idea of this library is to be used on developer's machine for communication with iOS devices, so you shouldn't need it in your native application. May I ask why you have added `ios-device-lib` in the dependencies section of your NativeScript application?

**Comment by TimHawkHodg** [comment] 2018-01-16 14:55
@rosen-vladimirov I appreciate the support. So ios-device-lib used to be in my dependency section of the package.json but I deleted it. However each time I run `npm i` I can see the ios-device-lib being added to the package.lock.json. Also explicitly naming the provisioning profile on the build does NOT solve the issue. After much trial and error I have found how to resolve this issue.

Try these two things: 
(1)
`npm uninstall ios-device-lib adb --save`
`Remove and then re-add the ios platform`
`tns run ios`

(2)
If one does not solve the issue then go to 

node_modules > nativescript > node_modules >ios-device-lib . Delete this directory

node_modules > nativescript > lib > common > resources > platform-tools > android .

Inside this folder there should be 3 folders with each containing an adb.exe. Delete them.

`tns run ios`

Should work.

@rosen-vladimirov What I don't understand is why I am getting android debug bridge errors when I am trying to run my iOS project?

**Comment by rosen-vladimirov** [comment] 2018-01-16 15:29
Hey @TimHawkHodg , 
The problem is that you have `nativescript` as dependency of your project. The `nativescript` package is the CLI itself and it should not be included in your NativeScript application. The CLI should be installed globally (`npm install -g nativescript`). It looks like, you've missed the `-g` part at some point and that's why you have the package included in your project.
In order to resolve the issue, just execute `npm uninstall --save nativescript` in your project dir. This way `ios-device-lib` and `adb` will be removed from your project.

As per your last question - whenever you try building your NativeScript application for iOS , CLI analyzes your dependencies and includes them in the native Xcode project. In your case this includes all CLI dependencies (like ios-device-lib, adb, etc.). These are binaries, and as I've explained in my previous answer, Xcode tries to codesign them.

Can you please try the suggested solution and see if it works for you?

**Comment by rosen-vladimirov** [comment] 2018-01-16 15:52
Closing this issue as the suggested fix worked as reported [here](https://github.com/NativeScript/nativescript-cli/issues/3173#issuecomment-358004614)

**Closed as completed by rosen-vladimirov** 2018-01-16 15:52 UTC
Labels: question
